import test from "node:test";
import assert from "node:assert/strict";

import { toChineseHint } from "../src/hints.mjs";

test("Chinese hints preserve child-facing meaning across audited grammar categories", () => {
  const examples = new Map([
    ["The woman is writing a note.", "女人正在写一张便条。"],
    ["The girl is drawing a house.", "女孩正在画一座房子。"],
    ["The boy is opening a box.", "男孩正在打开一个盒子。"],
    ["There are two children.", "有两个孩子。"],
    ["There are three students.", "有三个学生。"],
    ["Two red pigs are in the pen.", "两只红色的猪在围栏里。"],
    ["The child is raising two hands.", "孩子正在举起两只手。"],
    ["This is a pair of shorts.", "这是一条短裤。"],
    ["This is a dress.", "这是一件连衣裙。"],
    ["The child has two socks.", "孩子有两只袜子。"],
    ["This is soap.", "这是肥皂。"],
    ["This is toothpaste.", "这是牙膏。"],
    ["This is hand cream.", "这是护手霜。"],
    ["This is my mother.", "这是我的妈妈。"],
    ["She is my mother.", "她是我的妈妈。"],
    ["The woman is my mother.", "这个女人是我的妈妈。"],
    ["My mother is a woman.", "我的妈妈是女人。"],
    ["She is my older sister.", "她是我的姐姐。"],
    ["He is my younger brother.", "他是我的弟弟。"],
    ["The baby is my little brother.", "宝宝是我的弟弟。"],
    ["I have two sisters.", "我有两个姐妹。"],
    ["We are brother and sister.", "我们是兄妹。"],
    ["The two babies are twins.", "两个宝宝是双胞胎。"],
    ["The grandma and grandpa are grandparents.", "奶奶和爷爷是祖父母。"],
    ["The duck is flying.", "鸭子正在飞翔。"],
    ["The boy is flying a kite.", "男孩正在放风筝。"],
    ["The children are sitting together.", "孩子们正坐在一起。"],
    ["The family is standing apart.", "一家人分开站着。"],
    ["The girl is folding a blanket.", "女孩正在叠一条毯子。"],
    ["The boy is putting on a shirt.", "男孩正在穿衬衫。"],
    ["The boy is taking off a shirt.", "男孩正在脱衬衫。"],
    ["The child is getting out of bed.", "孩子正在下床。"],
    ["The boy is taking a shower.", "男孩正在洗澡。"],
    ["The student is writing with a pencil.", "学生正在用铅笔写字。"],
    ["This is an orange.", "这是一个橙子。"],
    ["This is a bowl of rice.", "这是一碗米饭。"],
    ["This is a glass of milk.", "这是一杯牛奶。"],
    ["There is bread and milk on the table.", "桌子上有面包和牛奶。"],
    ["The bird is flying in the sky.", "鸟正在天空中飞翔。"],
    ["The car is on the road.", "小汽车在路上。"],
    ["The girl has sunglasses on her face.", "女孩脸上戴着太阳镜。"],
    ["The child has a bandage on the knee.", "孩子的膝盖上贴着创可贴。"],
    ["The child is playing table tennis.", "孩子正在打乒乓球。"],
    ["The child is skipping rope.", "孩子正在跳绳。"],
    ["The child is riding in a car.", "孩子正坐在汽车里。"],
    ["The child is getting off the train.", "孩子正在下火车。"],
    ["The child is drawing a line.", "孩子正在画一条线。"],
    ["The girl is cutting the line.", "女孩正在插队。"],
    ["The child is giving water to a friend.", "孩子正在给朋友水。"],
    ["The girl is taking a book from the shelf.", "女孩正在从书架上拿一本书。"],
    ["The boy likes apple juice.", "男孩喜欢苹果汁。"],
    ["The child likes drawing a house.", "孩子喜欢画房子。"],
    ["The child is turning on a lamp.", "孩子正在开灯。"],
    ["The ruler is sticking out of the bag.", "尺子从书包里露出来。"],
    ["The child is ready for school.", "孩子准备好上学了。"],
    ["The child is resting after school.", "孩子正在放学后休息。"],
    ["The classmates are putting books away.", "同学们正在收好书。"],
    ["The family is leaving home in the morning.", "一家人早上正在离开家。"],
    ["The mother is reading with the child.", "妈妈正和孩子一起读书。"],
    ["The girl is reading a card.", "女孩正在读一张卡片。"],
    ["The boy is kicking a beanbag.", "男孩正在踢一个豆袋。"],
    ["The child is running at home.", "孩子正在家里跑步。"],
    ["The children are playing in the park.", "孩子们正在公园里玩。"],
    ["The table is low.", "桌子很矮。"],
    ["The toy box has balls inside.", "玩具盒里有球。"],
    ["Everyone is in the family picture.", "所有人都在全家福里。"],
    ["It is sunny.", "天气晴朗。"],
    ["It is raining.", "正在下雨。"],
    ["The boy has a kite in the wind.", "男孩正在风中放风筝。"],
    ["The woman has an umbrella in the rain.", "女人正在雨中撑着伞。"],
    ["The child has a bandage on the hand.", "孩子的手上贴着创可贴。"],
    ["The chair is far from the desk.", "椅子离课桌很远。"],
    ["This is my friend.", "这是我的朋友。"],
    ["The lunch box has fruit inside.", "午餐盒里有水果。"],
    ["The girl has a scarf around her head.", "女孩的头上围着围巾。"],
    ["The boy has a cap on his head.", "男孩的头上戴着一顶帽子。"],
    ["The father is filling a bowl with rice.", "爸爸正在往碗里盛米饭。"],
    ["The grandpa is walking with a brown dog.", "爷爷正和棕色的狗一起走路。"],
    ["The baby is sitting with bare feet.", "宝宝光脚坐着。"],
    ["The child is smiling with clean teeth.", "孩子微笑时露出干净的牙齿。"],
    ["The girl is with her friend.", "女孩和朋友在一起。"],
    ["The boy is building with a classmate.", "男孩正和同学一起搭东西。"],
    ["The friends are sitting with a rope.", "朋友们拿着绳子坐着。"],
    ["The girl is helping with a schoolbag.", "女孩正在帮忙整理书包。"],
    ["The girl is helping a classmate with shoes.", "女孩正在帮助同学穿鞋。"],
    ["The children are taking turns with a scooter.", "孩子们正在轮流玩滑板车。"],
    ["The child is going home with a parent.", "孩子正和家长一起回家。"],
    ["The child is happy with a toy.", "孩子拿着玩具，感到开心。"],
    ["The bag is heavy with books.", "书包里装着很多书，所以很重。"],
    ["The girl is sharing a book with a friend.", "女孩正在和朋友分享一本书。"],
    ["The father is helping with homework.", "爸爸正在帮忙做作业。"],
    ["The mother is cooking with the child.", "妈妈正在和孩子一起做饭。"],
    ["The students are ready for the next lesson.", "学生们准备好开始下一节课了。"],
    ["The girl is walking home after school.", "女孩放学后正步行回家。"],
    ["The family has dinner at the table.", "一家人正在桌边吃晚饭。"],
    ["The girl has a bunch of grapes.", "女孩有一串葡萄。"],
    ["The girl is putting on her shoes at home.", "女孩正在家里穿上鞋子。"],
    ["The girl is taking a spoon out of a bowl.", "女孩正在从碗里拿出一把勺子。"],
    ["The boy is putting on a cap.", "男孩正在戴上鸭舌帽。"],
    ["The girl is walking home.", "女孩正在步行回家。"],
    ["The girl has sunglasses in the sun.", "女孩在阳光下戴着太阳镜。"],
    ["The boy has a blue cap in his hand.", "男孩手里拿着一顶蓝色帽子。"],
    ["The baby has socks on both hands.", "宝宝的双手穿着袜子。"],
    ["The student is putting away a schoolbag.", "学生正在收好书包。"],
    ["The woman is getting off the train.", "女人正在下火车。"],
    ["The child is ready after washing.", "孩子洗好后准备就绪。"],
    ["The children are ready in coats.", "孩子们穿好外套，准备好了。"],
    ["The boy is putting the bag on a chair.", "男孩正在把书包放在椅子上。"],
    ["The schoolbag is ready by the door.", "书包已经准备好，放在门旁边。"],
    ["The clothes are ready on the bed.", "衣服已经准备好，放在床上。"],
    ["The children are taking turns on the slide.", "孩子们正在轮流玩滑梯。"],
    ["The classmates are making a paper chain.", "同学们正在制作一条纸链。"],
    ["Two friends are making the table messy.", "朋友们正在把桌子弄乱。"],
    ["The classmates are pulling books out.", "同学们正在把书拿出来。"],
    ["The boy is giving a notebook back.", "男孩正在归还一本笔记本。"],
    ["The family is coming home in the evening.", "一家人晚上正在回家。"],
    ["The class is walking back to the classroom.", "全班正在走回教室。"],
    ["The girl is taking a crayon from a friend.", "女孩正在从朋友那里拿一支蜡笔。"],
    ["The boy is carrying books for a classmate.", "男孩正在帮同学拿书。"],
    ["The girl is playing table tennis.", "女孩正在打乒乓球。"],
    ["The boy is skipping rope.", "男孩正在跳绳。"],
    ["The children are running a race.", "孩子们正在进行赛跑。"],
    ["The boy is standing at the finish line.", "男孩正站在终点线旁。"],
    ["The girl is erasing a line.", "女孩正在擦掉一条线。"],
    ["The girl is waiting in line.", "女孩正在排队等待。"]
  ]);

  for (const [sentence, expected] of examples) {
    assert.equal(toChineseHint(sentence), expected, sentence);
  }
});
